# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62roker.proto\"\x07\n\x05\x45mpty\"/\n\tAudioFile\x12\x0f\n\x07\x61udioid\x18\x01 \x01(\x03\x12\x11\n\taudiofile\x18\x02 \x01(\x0c\x32\'\n\tsend_file\x12\x1a\n\x04Send\x12\x06.Empty\x1a\n.AudioFileb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_AUDIOFILE = DESCRIPTOR.message_types_by_name['AudioFile']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'broker_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

AudioFile = _reflection.GeneratedProtocolMessageType('AudioFile', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOFILE,
  '__module__' : 'broker_pb2'
  # @@protoc_insertion_point(class_scope:AudioFile)
  })
_sym_db.RegisterMessage(AudioFile)

_SEND_FILE = DESCRIPTOR.services_by_name['send_file']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=16
  _EMPTY._serialized_end=23
  _AUDIOFILE._serialized_start=25
  _AUDIOFILE._serialized_end=72
  _SEND_FILE._serialized_start=74
  _SEND_FILE._serialized_end=113
# @@protoc_insertion_point(module_scope)
